### ISSUE TITLE
RTT calculation

### ISSUE THREAD

**Issue by karishmas26** [USAID-OHA-SI/Aging#5]
https://github.com/USAID-OHA-SI/Aging/blob/1a351ffa0808c69e9146fe47465b560e60b2f7f0/aging.qmd#L388

is there supposed to be a `ltfu` condition in this line?

**Comment by achafetz** [comment]
Sorry this isn't clear. With a Boolean in R, you don't technically have to write out the statement. So in this `case_when()` statement, just writing `ltfu` is equivalent to `ltfu == TRUE`

```
x <- TRUE

ifelse(x, "IT'S TRUE", "Whoops")
```
